---
sudo: false
language: ruby
cache: bundler
matrix:
  fast_finish: false
  include:
    - rvm: 3.0.1
      env: RUBYOPT=--verbose --enable-frozen-string-literal
    - rvm: ruby-head
      env: RUBYOPT=--verbose --enable-frozen-string-literal

    # JRuby and Truffleruby don't support keyword argument semantics of ruby-3.0

script:
  - bundle exec rake test TESTOPTS=-v
